ALTER TABLE "posts"
ADD COLUMN "visibility" TEXT NOT NULL DEFAULT 'PUBLIC',
ADD COLUMN "allowComments" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "moments"
ADD COLUMN "allowComments" BOOLEAN NOT NULL DEFAULT true;
