/**
 * Jest global setup — mock @prisma/client enums so tests can run
 * without running `prisma generate` (which fails due to a schema bug).
 * In production, these enums are generated by Prisma. For testing,
 * we provide string-enum equivalents.
 */
jest.mock('@prisma/client', () => ({
  // Enum: HealthRecordType
  HealthRecordType: {
    VACCINE: 'VACCINE',
    DEWORMING: 'DEWORMING',
    CHECKUP: 'CHECKUP',
    VISIT: 'VISIT',
  },
  // Enum: ReminderType
  ReminderType: {
    VACCINE: 'VACCINE',
    DEWORMING: 'DEWORMING',
    CHECKUP: 'CHECKUP',
  },
  // Enum: ReminderStatus
  ReminderStatus: {
    PENDING: 'PENDING',
    NOTIFIED: 'NOTIFIED',
    OVERDUE: 'OVERDUE',
    DONE: 'DONE',
  },
  // Enum: NotificationType
  NotificationType: {
    REMINDER: 'REMINDER',
    LIKE: 'LIKE',
    COMMENT: 'COMMENT',
    FOLLOW: 'FOLLOW',
    SYSTEM: 'SYSTEM',
  },
  // Enum: CircleType
  CircleType: {
    BREED: 'BREED',
    CITY: 'CITY',
    TOPIC: 'TOPIC',
  },
  // Enum: SessionStatus
  SessionStatus: {
    OBSERVING: 'OBSERVING',
    RECOVERED: 'RECOVERED',
    VISITED_DOCTOR: 'VISITED_DOCTOR',
  },
  // Enum: MembershipLevel
  MembershipLevel: {
    FREE: 'FREE',
    PREMIUM: 'PREMIUM',
  },
  // Enum: PetSpecies
  PetSpecies: {
    DOG: 'DOG',
    CAT: 'CAT',
  },
  // Enum: PetGender
  PetGender: {
    MALE: 'MALE',
    FEMALE: 'FEMALE',
  },
  // Enum: CircleVisibility (Reddit-style)
  CircleVisibility: {
    PUBLIC: 'PUBLIC',
    RESTRICTED: 'RESTRICTED',
    PRIVATE: 'PRIVATE',
  },
  // Enum: CircleMemberRole
  CircleMemberRole: {
    MEMBER: 'MEMBER',
    MODERATOR: 'MODERATOR',
    OWNER: 'OWNER',
  },
  // Enum: CircleMemberStatus
  CircleMemberStatus: {
    ACTIVE: 'ACTIVE',
    BANNED: 'BANNED',
    KICKED: 'KICKED',
  },
  // PrismaClient constructor (mocked)
  PrismaClient: jest.fn(() => ({})),
}));
